@startuml

class Dibujo{
    + Imprimir
    }
Class Conductor {
    + Conducir ()
    + RecogerMonedas ()
    + RecogerGemas ()
    + UsarPropulsor ()
    + RecargarCombustible ()
    }
Class Vehiculo{
    + RecorrerTerreno(Terreno terreno)
    + Mejorar(Motor motor)
    + Mejorar(Suspensión suspensión)
    + Mejorar(NeumaticoMejora neumaticos)
    + Mejorar(T4r t4r)
    + ActivarNitro(Propulsor nitro)
    + UsarDobleSalto(Propulsor dobleSalto)
    + UsarAgarre(Propulsor agarre)
    + UsarPlaneador(Propulsor planeador)
     }
Class HillClimber

Class Etapa{
    + Obstaculizar ()
}
Class Campo

Class PiezaDeOpmiizacion{
    + Mejorar Vehiculo ()
}
Class Motor{
    + AumentarVelocidad ()
}
Class Suspensión{
    + MantenerRuedasEnTerreno ()
}
Class NeumaticoMejora{
    + AumentarAdeherencia ()

}
Class T4r{
    + Mejorar4x4 ()
}

Class Iteam{
    + Recoger ()
}
Class Moneda{
    + Recoger ()
    + Gastar ()
}
Class Gema{
    + Recoger ()
    + Gastar ()
}
Class Gasolina{
    + Recoger ()
    + Recargar ()
}

Class Propulsor{
    + Activar ()
}
Class Nitro {
    + Activar ()
}
Class DobleSalto{
    + Activar ()
}
Class NeumaticoPropulsor{
    + Activar ()
}
Class Agarre{
    + Activar ()
}
Class Planeador{
    + Activar ()
}

Class Medidor{
    + Leer ()
    + Medir ()
}
Class Metro{
    + Leer ()
    + Medir ()
}
Class Boost{
    + Leer ()
    + Medir ()
}
Class Rpm{
    + Leer ()
    + Medir ()
}

Class Controlador{
    + Mandar ()
}
Class Freno{
    + Frenar ()
}
Class Acelerador{
    + Acelerar ()
}

Vehiculo <|-- HillCliber
Etapa <|-- Campo
PiezaDeOptimizacion <|-- Motor
PiezaDeOptimizacion <|-- Suspensión
PiezaDeOptimizacion <|-- NeumaticoMejora
PiezaDeOptimizacion <|--T4r
Iteam <|-- Moneda 
Iteam <|-- Gema
Iteam <|-- Gasolina
Propulsor <|-- Nitro
Propulsor <|-- DobleSalto
Propulsor <|-- NeumaticoPropulsor
Propulsor <|-- Agarre
Propulsor <|-- Planeador
Medidor <|-- Metro
Medidor <|-- Boost
Medidor <|-- Rpm
Controlador <|-- Freno
Controlador <|-- Acelerador
Dibujo <|--Conductor
Dibujo <|--Vehiculo
Dibujo <|--HillClimber
Dibujo <|--Etapa
Dibujo <|--Campo
Dibujo <|--PiezaDeOpmiizacion
Dibujo <|--Motor
Dibujo <|--Suspensión
Dibujo <|--NeumaticoMejora
Dibujo <|--T4r
Dibujo <|--Iteam
Dibujo <|--Moneda
Dibujo <|--Gema
Dibujo <|--Gasolina
Dibujo <|--Propulsor
Dibujo <|--Nitro
Dibujo <|--DobleSalto
Dibujo <|--NeumaticoPropulsor
Dibujo <|--Agarre
Dibujo <|--Planeador
Dibujo <|--Medidor
Dibujo <|--Metro
Dibujo <|--Boost
Dibujo <|--Rpm
Dibujo <|--Controlador
Dibujo <|--Freno
Dibujo <|--Acelerador


Moneda"*"--* "1"Etapa
Gema"*"--* "1"Etapa
Gasolina"*"--* "1"Etapa
Metro "1"--* "1" Etapa
Boost "1"--* "1"Etapa
Rpm "1"--* "1"Etapa
Freno "1"--* "1"Etapa
Acelerador "1"--* "1"Etapa
Moneda"*"--* "1"Campo
Gema"*"--* "1"Campo
Gasolina"*"--* "1"Campo
Metro "1"--* "1"Campo
Boost "1"--* "1"Campo
Rpm "1"--* "1"Campo
Freno "1"--* "1"Campo
Acelerador"1"--* "1" Campo
Motor "*"--* "1"Vehiculo
Motor "*"--* "1"HillClimber
Suspensión "*"--* "1" Vehiculo
Suspensión "*"--* "1"HillClimber
NeumaticoMejora "*"--* "1"Vehiculo
NeumaticoMejora"*"--* "1" HillClimber
T4r "*"--* "1"Vehiculo
T4r "*"--* "1"HillClimber
Freno"1"--* "*" Vehiculo
Freno"1"--* "1"HillClimber
Acelerador"1"--* "*" Vehiculo
Acelerador"1"--* "1" HillClimber

Conductor "1" o-- "*" Vehiculo
Conductor "1" o-- "1" HillClimber
Conductor "1" o-- "*" Etapa
Conductor "1" o-- "1" Campo
Conductor "1" o-- "1" Moneda
Conductor "1" o-- "1"  Gema
Conductor "1" o-- "1"  Gasolina
Nitro "1" --o "*" Vehiculo
Nitro"1" --o "1"HillClimber
DobleSalto"1" --o "*" Vehiculo
DobleSalto"1" --o "1"HillClimber
NeumaticoPropulsor"1" --o "*" Vehiculo
NeumaticoPropulsor"1" --o "1" HillClimber
Agarre "1"--o "1"Vehiculo
Agarre "1" --o "1"HillClimber
Planeador "1" --o "1"Vehiculo
Planeador "1" --o "1"HillClimber
Conductor "1" o-- "1" Controlador
Conductor "1" o-- "1" Freno
Conductor "1" o-- "1" Acelerador

@enduml